PR Feature/add pom.xml
hkt5/documents pull request #1
Opened 2022-03-13 18:36 UTC by gruhol

2022-03-13 19:43 UTC, hkt5 requested changes

2022-03-13 19:43 UTC, hkt5 commented on pom.xml
> +        <jdk.version>1.8</jdk.version>
Czy my chcemy pisać serio w javie 8?

2022-03-13 22:25 UTC, gruhol commented on pom.xml
> +        <jdk.version>1.8</jdk.version>
Czyli <jdk.version>11</jdk.version>?

2022-03-14 18:03 UTC, hkt5 commented on pom.xml
> +        <jdk.version>1.8</jdk.version>
tak lub 17

2022-03-15 08:28 UTC, merged